import { contextBridge, ipcRenderer } from "electron";
import type {
  AutopilotStartDataRunInput,
  CapabilityUpdateInput,
  IdentityContext,
  MemoryAddInput,
  MemoryImportInput,
  MemoryRecallFeedbackInput,
  MemoryReplayRecallInput,
  MemorySearchQuery,
  MemoryUpdateInput,
  McpConfigTransfer,
  McpServerInput,
  McpServerUpdate,
  ModelConfigUpdate,
  PermissionMode,
  PermissionRule,
  PersonalityConfig,
  ProjectCreateInput,
  ProjectUpdateInput,
  RemoteBridgeConfig,
  ScheduledJobInput,
  SendPromptInput,
  ServstationA2AConfigUpdate,
  ServstationA2AOidcLoginInput,
  SubagentConfig,
  SupbotEvent,
  ToolMarketConfigUpdate,
  ToolMarketQuery
} from "@supbot/shared";

const api = {
  snapshot: () => ipcRenderer.invoke("snapshot"),
  createConversation: (title?: string) => ipcRenderer.invoke("conversation:create", title),
  deleteConversation: (id: string) => ipcRenderer.invoke("conversation:delete", id),
  sendPrompt: (input: SendPromptInput) => ipcRenderer.invoke("prompt:send", input),
  cancelJob: (id: string) => ipcRenderer.invoke("job:cancel", id),
  approveToolPermission: (id: string) => ipcRenderer.invoke("tool:approve", id),
  denyToolPermission: (id: string) => ipcRenderer.invoke("tool:deny", id),
  setPermissionMode: (mode: PermissionMode) => ipcRenderer.invoke("permission:setMode", mode),
  addPermissionRule: (rule: Omit<PermissionRule, "id" | "createdAt" | "scope"> & { id?: string }) => ipcRenderer.invoke("permission:addRule", rule),
  removePermissionRule: (id: string) => ipcRenderer.invoke("permission:removeRule", id),
  compactConversation: (id: string) => ipcRenderer.invoke("conversation:compact", id),
  loadTranscript: (id: string) => ipcRenderer.invoke("conversation:loadTranscript", id),
  createProjectFromFolder: (input: ProjectCreateInput) => ipcRenderer.invoke("project:createFromFolder", input),
  listProjects: () => ipcRenderer.invoke("project:list"),
  pickProjectFolder: () => ipcRenderer.invoke("project:pickFolder"),
  openProject: (id: string) => ipcRenderer.invoke("project:open", id),
  updateProject: (id: string, input: ProjectUpdateInput) => ipcRenderer.invoke("project:update", id, input),
  startAutopilotDataRun: (input: AutopilotStartDataRunInput) => ipcRenderer.invoke("autopilot:startDataRun", input),
  pauseAutopilotRun: (id: string) => ipcRenderer.invoke("autopilot:pause", id),
  resumeAutopilotRun: (id: string) => ipcRenderer.invoke("autopilot:resume", id),
  cancelAutopilotRun: (id: string) => ipcRenderer.invoke("autopilot:cancel", id),
  getAutopilotRunReport: (id: string) => ipcRenderer.invoke("autopilot:getRunReport", id),
  listWorktrees: () => ipcRenderer.invoke("worktree:list"),
  getWorktreeDiff: (id: string) => ipcRenderer.invoke("worktree:getDiff", id),
  applyWorktree: (id: string) => ipcRenderer.invoke("worktree:apply", id),
  discardWorktree: (id: string) => ipcRenderer.invoke("worktree:discard", id),
  openWorktreeFolder: (id: string) => ipcRenderer.invoke("worktree:openFolder", id),
  getRemoteBridgeConfig: () => ipcRenderer.invoke("remoteBridge:getConfig"),
  updateRemoteBridgeConfig: (input: Partial<RemoteBridgeConfig> & { token?: string; clearToken?: boolean }) => ipcRenderer.invoke("remoteBridge:updateConfig", input),
  listRemoteBridgeSessions: () => ipcRenderer.invoke("remoteBridge:listSessions"),
  revokeRemoteBridgeSession: (id: string) => ipcRenderer.invoke("remoteBridge:revokeSession", id),
  listRemoteBridgeAudit: () => ipcRenderer.invoke("remoteBridge:listAudit"),
  getIdentityContext: () => ipcRenderer.invoke("identity:get"),
  updateIdentityContext: (input: IdentityContext) => ipcRenderer.invoke("identity:update", input),
  getServstationA2AConfig: () => ipcRenderer.invoke("servstationA2A:getConfig"),
  updateServstationA2AConfig: (input: ServstationA2AConfigUpdate) => ipcRenderer.invoke("servstationA2A:updateConfig", input),
  loginServstationOidc: (input?: ServstationA2AOidcLoginInput) => ipcRenderer.invoke("servstationA2A:loginOidc", input),
  refreshServstationOidc: () => ipcRenderer.invoke("servstationA2A:refreshOidc"),
  logoutServstationOidc: () => ipcRenderer.invoke("servstationA2A:logoutOidc"),
  connectServstationReverseBridge: () => ipcRenderer.invoke("servstationA2A:connectReverse"),
  disconnectServstationReverseBridge: () => ipcRenderer.invoke("servstationA2A:disconnectReverse"),
  listMemory: (query?: MemorySearchQuery) => ipcRenderer.invoke("memory:list", query),
  searchMemory: (query?: MemorySearchQuery) => ipcRenderer.invoke("memory:search", query),
  addMemory: (input: MemoryAddInput) => ipcRenderer.invoke("memory:add", input),
  updateMemory: (id: string, input: MemoryUpdateInput) => ipcRenderer.invoke("memory:update", id, input),
  deleteMemory: (id: string) => ipcRenderer.invoke("memory:delete", id),
  approveMemoryCandidate: (id: string) => ipcRenderer.invoke("memory:approveCandidate", id),
  denyMemoryCandidate: (id: string) => ipcRenderer.invoke("memory:denyCandidate", id),
  exportMemory: () => ipcRenderer.invoke("memory:export"),
  importMemory: (input: MemoryImportInput) => ipcRenderer.invoke("memory:import", input),
  backupMemory: () => ipcRenderer.invoke("memory:backup"),
  restoreMemory: (filePath?: string) => ipcRenderer.invoke("memory:restore", filePath),
  replayMemoryRecall: (input: MemoryReplayRecallInput) => ipcRenderer.invoke("memory:replayRecall", input),
  evaluateMemoryRecall: (input: MemoryReplayRecallInput) => ipcRenderer.invoke("memory:evaluateRecall", input),
  addMemoryRecallFeedback: (input: MemoryRecallFeedbackInput) => ipcRenderer.invoke("memory:addRecallFeedback", input),
  updateModelConfig: (input: ModelConfigUpdate) => ipcRenderer.invoke("model:update", input),
  testModelConfig: (input?: Partial<ModelConfigUpdate>) => ipcRenderer.invoke("model:test", input),
  updateToolMarketConfig: (input: ToolMarketConfigUpdate) => ipcRenderer.invoke("market-config:update", input),
  updatePersonality: (input: PersonalityConfig) => ipcRenderer.invoke("personality:update", input),
  updateCapability: (id: string, input: CapabilityUpdateInput) => ipcRenderer.invoke("capability:update", id, input),
  deleteCapability: (id: string) => ipcRenderer.invoke("capability:delete", id),
  saveSubagent: (input: SubagentConfig) => ipcRenderer.invoke("subagent:save", input),
  deleteSubagent: (id: string) => ipcRenderer.invoke("subagent:delete", id),
  listToolMarket: (query?: ToolMarketQuery) => ipcRenderer.invoke("market:list", query),
  installToolMarketProduct: (id: string) => ipcRenderer.invoke("market:install", id),
  uninstallToolMarketProduct: (id: string) => ipcRenderer.invoke("market:uninstall", id),
  listMcpServers: () => ipcRenderer.invoke("mcp:listServers"),
  addMcpServer: (input: McpServerInput) => ipcRenderer.invoke("mcp:addServer", input),
  updateMcpServer: (id: string, input: McpServerUpdate) => ipcRenderer.invoke("mcp:updateServer", id, input),
  removeMcpServer: (id: string) => ipcRenderer.invoke("mcp:removeServer", id),
  connectMcpServer: (id: string) => ipcRenderer.invoke("mcp:connect", id),
  disconnectMcpServer: (id: string) => ipcRenderer.invoke("mcp:disconnect", id),
  refreshMcpTools: (id: string) => ipcRenderer.invoke("mcp:refreshTools", id),
  getMcpLogs: (id: string) => ipcRenderer.invoke("mcp:getLogs", id),
  listMcpPresets: () => ipcRenderer.invoke("mcp:listPresets"),
  exportMcpConfig: () => ipcRenderer.invoke("mcp:export"),
  importMcpConfig: (input: McpConfigTransfer) => ipcRenderer.invoke("mcp:import", input),
  diagnoseMcpServer: (input: McpServerInput) => ipcRenderer.invoke("mcp:diagnoseServer", input),
  createScheduledJob: (input: ScheduledJobInput) => ipcRenderer.invoke("schedule:create", input),
  updateScheduledJob: (id: string, input: Partial<ScheduledJobInput>) => ipcRenderer.invoke("schedule:update", id, input),
  deleteScheduledJob: (id: string) => ipcRenderer.invoke("schedule:delete", id),
  pickAttachments: () => ipcRenderer.invoke("attachment:pick"),
  openFile: (filePath: string) => ipcRenderer.invoke("file:open", filePath),
  userDataPath: () => ipcRenderer.invoke("path:userData"),
  onEvent: (listener: (event: SupbotEvent) => void) => {
    const wrapped = (_event: unknown, payload: SupbotEvent) => listener(payload);
    ipcRenderer.on("supbot:event", wrapped);
    return () => ipcRenderer.off("supbot:event", wrapped);
  }
};

contextBridge.exposeInMainWorld("supbot", api);
